In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [8]:
df = sns.load_dataset('tips')

In [10]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [12]:
from sklearn.preprocessing import StandardScaler

In [14]:
scaler=StandardScaler()

In [16]:
scaler

StandardScaler()

In [18]:
df['total_bill'].head()

0    16.99
1    10.34
2    21.01
3    23.68
4    24.59
Name: total_bill, dtype: float64

In [22]:
scaler.fit(df[['total_bill']])

StandardScaler()

In [26]:
scaler.transform(df[['total_bill']])

array([[-3.14711305e-01],
       [-1.06323531e+00],
       [ 1.37779900e-01],
       [ 4.38315103e-01],
       [ 5.40744704e-01],
       [ 6.19536705e-01],
       [-1.23995452e+00],
       [ 7.98507107e-01],
       [-5.34203307e-01],
       [-5.63468908e-01],
       [-1.07111451e+00],
       [ 1.74175992e+00],
       [-4.91430507e-01],
       [-1.52624903e-01],
       [-5.57840908e-01],
       [ 2.01939101e-01],
       [-1.06436091e+00],
       [-3.93503306e-01],
       [-3.16962505e-01],
       [ 9.72582994e-02],
       [-2.10030504e-01],
       [ 5.67366990e-02],
       [-4.52034507e-01],
       [ 2.21000952e+00],
       [ 3.83349840e-03],
       [-2.22412104e-01],
       [-7.22178510e-01],
       [-7.98719310e-01],
       [ 2.15446301e-01],
       [-1.53017018e-02],
       [-1.15215771e+00],
       [-1.61629703e-01],
       [-5.31952107e-01],
       [ 1.01760699e-01],
       [-2.25788904e-01],
       [ 4.81087904e-01],
       [-3.91252106e-01],
       [-3.21464905e-01],
       [-1.2

In [32]:
scaler.fit_transform(df[['total_bill','tip']])

array([[-3.14711305e-01, -1.43994695e+00],
       [-1.06323531e+00, -9.69205340e-01],
       [ 1.37779900e-01,  3.63355539e-01],
       [ 4.38315103e-01,  2.25754144e-01],
       [ 5.40744704e-01,  4.43019505e-01],
       [ 6.19536705e-01,  1.23965916e+00],
       [-1.23995452e+00, -7.22971264e-01],
       [ 7.98507107e-01,  8.81527488e-02],
       [-5.34203307e-01, -7.51939979e-01],
       [-5.63468908e-01,  1.67816714e-01],
       [-1.07111451e+00, -9.32994446e-01],
       [ 1.74175992e+00,  1.44968234e+00],
       [-4.91430507e-01, -1.03438495e+00],
       [-1.52624903e-01,  1.24660453e-03],
       [-5.57840908e-01,  1.57309619e-02],
       [ 2.01939101e-01,  6.67527044e-01],
       [-1.06436091e+00, -9.61963161e-01],
       [-3.93503306e-01,  5.15441291e-01],
       [-3.16962505e-01,  3.63355539e-01],
       [ 9.72582994e-02,  2.54722859e-01],
       [-2.10030504e-01,  7.83401903e-01],
       [ 5.67366990e-02, -1.79807863e-01],
       [-4.52034507e-01, -5.56401155e-01],
       [ 2.

In [34]:
pd.DataFrame(scaler.fit_transform(df[['total_bill', 'tip']]), columns = ['total_bill', 'tip'])

total_bill       tip
0     -0.314711 -1.439947
1     -1.063235 -0.969205
2      0.137780  0.363356
3      0.438315  0.225754
4      0.540745  0.443020
..          ...       ...
239    1.040511  2.115963
240    0.832275 -0.722971
241    0.324630 -0.722971
242   -0.221287 -0.904026
243   -0.113229  0.001247

[244 rows x 2 columns]

In [38]:
#new data -> just transform 
scaler.transform([[13,2]])

array([[-0.76382571, -0.72297126]])

In [40]:
#Normalization 
from sklearn.preprocessing import MinMaxScaler

In [46]:
min_max=MinMaxScaler()

In [48]:
min_max

MinMaxScaler()

In [50]:
min_max.fit_transform(df[['total_bill','tip']])

array([[0.29157939, 0.00111111],
       [0.1522832 , 0.07333333],
       [0.3757855 , 0.27777778],
       [0.43171345, 0.25666667],
       [0.45077503, 0.29      ],
       [0.46543779, 0.41222222],
       [0.11939673, 0.11111111],
       [0.49874319, 0.23555556],
       [0.25073314, 0.10666667],
       [0.24528697, 0.24777778],
       [0.15081693, 0.07888889],
       [0.67427734, 0.44444444],
       [0.25869292, 0.06333333],
       [0.32174277, 0.22222222],
       [0.24633431, 0.22444444],
       [0.38772518, 0.32444444],
       [0.15207373, 0.07444444],
       [0.27691663, 0.30111111],
       [0.29116045, 0.27777778],
       [0.36824466, 0.26111111],
       [0.31105991, 0.34222222],
       [0.36070381, 0.19444444],
       [0.2660243 , 0.13666667],
       [0.761416  , 0.73111111],
       [0.35085882, 0.24222222],
       [0.30875576, 0.14888889],
       [0.21575199, 0.11111111],
       [0.20150817, 0.11111111],
       [0.39023879, 0.36666667],
       [0.34729786, 0.22222222],
       [0.

In [52]:

min_max.transform([[13,1]])
     

array([[0.20800168, 0.        ]])

In [54]:
#Robust scaler ->Robust to outlier
from sklearn.preprocessing import RobustScaler
r_scale=RobustScaler()

In [56]:
r_scale

RobustScaler()

In [58]:
r_scale.fit_transform(df[['total_bill', 'tip']])

array([[-7.46753247e-02, -1.20960000e+00],
       [-6.91558442e-01, -7.93600000e-01],
       [ 2.98237477e-01,  3.84000000e-01],
       [ 5.45918367e-01,  2.62400000e-01],
       [ 6.30333952e-01,  4.54400000e-01],
       [ 6.95269017e-01,  1.15840000e+00],
       [-8.37198516e-01, -5.76000000e-01],
       [ 8.42764378e-01,  1.40800000e-01],
       [-2.55565863e-01, -6.01600000e-01],
       [-2.79684601e-01,  2.11200000e-01],
       [-6.98051948e-01, -7.61600000e-01],
       [ 1.62012987e+00,  1.34400000e+00],
       [-2.20315399e-01, -8.51200000e-01],
       [ 5.89053803e-02,  6.40000000e-02],
       [-2.75046382e-01,  7.68000000e-02],
       [ 3.51113173e-01,  6.52800000e-01],
       [-6.92486085e-01, -7.87200000e-01],
       [-1.39610390e-01,  5.18400000e-01],
       [-7.65306122e-02,  3.84000000e-01],
       [ 2.64842301e-01,  2.88000000e-01],
       [ 1.15955473e-02,  7.55200000e-01],
       [ 2.31447124e-01, -9.60000000e-02],
       [-1.87847866e-01, -4.28800000e-01],
       [ 2.